language: c

sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          compiler: gcc
          env: ERLANG_VERSION=21.2 ELIXIR_VERSION=1.8.1-otp-21
        - os: linux
          compiler: gcc
          env: ERLANG_VERSION=21.2 ELIXIR_VERSION=1.7.4-otp-21


before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get update -qq;
        sudo apt-get install -qq linux-headers-`uname -r`;
        git clone --depth=50 https://github.com/freemed/tty0tty.git;
        cd tty0tty/module && make && sudo cp tty0tty.ko /lib/modules/$(uname -r)/kernel/drivers/misc/;
        cd -;
        sudo depmod;
        sudo modprobe tty0tty;
        wget https://s3.amazonaws.com/travis-otp-releases/binaries/$(lsb_release -is | tr "A-Z" "a-z")/$(lsb_release -rs)/$(uname -m)/erlang-$ERLANG_VERSION-nonroot.tar.bz2;
        mkdir -p ~/otp && tar -xf erlang-$ERLANG_VERSION-nonroot.tar.bz2 -C ~/otp/;
        mkdir -p ~/.kerl;
        source $HOME/otp/$ERLANG_VERSION/activate;
        wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip;
        unzip -d elixir v$ELIXIR_VERSION.zip;
        sudo chmod 666 /dev/tnt*;
        ls -las /dev/tnt*;
      fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=`pwd`/elixir/bin:$PATH; fi

script:
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      ECALL_AUDIO_PORT=tnt0 ECALL_SIM_PORT=tnt1 mix test;
    fi
